name: osm_path_tracker_example
description: Example app for osm_path_tracker
publish_to: "none"

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  osm_path_tracker:
    path: ../   # 👈 means: use the local package!

flutter:
  uses-material-design: true
dev_dependencies:
  flutter_test:
    sdk: flutter
